#!/usr/bin/env python3

n = int(input())

a = [int(input()) for _ in range(n)]

cnts = [0, 0, 0, 0]
ans = 0

for element in a:
    if element % 6 == 0:
        ans += sum(cnts)
        cnts[3] += 1
    elif element % 3 == 0:
        ans += cnts[1] + cnts[3]
        cnts[2] += 1
    elif element % 2 == 0:
        ans += cnts[2] + cnts[3]
        cnts[1] += 1
    else:
        ans += cnts[3]
        cnts[0] += 1

print(ans)


