#!/usr/bin/env python3

s = ''
with open('input.txt', 'r') as file:
    s = file.read().replace('\n', '')

indexes = []
last = -1

for i in range(len(s)):
    if s[i] == 'D':
        if last != -1 and last != i - 1:
            indexes.append((last, i))
        last = i

res = min([r - l + 1 for (l, r) in indexes])

print(res)


