#!/usr/bin/env python3

n, m = map(int, input().split())
A = list(map(int, input().split()))
B = list(map(int, input().split()))

dp = [[0 for _ in range(m)]] * n

for i in range(n):
    if A[i] == B[0]:
        for j in range(i, n):
            dp[j][0] = 1
        break


for i in range(m):
    if B[i] == A[0]:
        for j in range(i, m):
            dp[0][j] = 1
        break

for i in range(1, n):
    for j in range(1, m):
        of = [dp[i][j - 1], dp[i - 1][j], dp[i - 1][j - 1]]
        if A[i] == B[j]:
            of[2] += 1
        dp[i][j] = max(of)


print(dp[n - 1][m - 1])
