#!/usr/bin/env python3

'''
Дан квадрат N x M, в каждой клетке которого напсиано целое число. Есть робот, который стартует в каком-то углу, ему нужно дойти до противоположного и собрать минимальное/максимальное число монет.
'''

N, M = map(int, input().split())

dp1, dp2, coins = [None] * N, [None] * N, [None] * N

for i in range(N):
    coins[i] = list(map(int, input().split()))
    dp1[i] = [0] * M
    dp2[i] = [0] * M

dp2[0][0] = dp1[0][0] = coins[0][0]

for y in range(1, N):
   dp2[y][0] = dp1[y][0] = dp1[y - 1][0] + coins[y][0]

for x in range(1, M):
   dp2[0][x] = dp1[0][x] = dp1[0][x - 1] + coins[0][x]

for y in range(1, N):
    for x in range(1, M):
        dp1[x][y] = max(dp1[x - 1][y], dp1[x][y - 1]) + coins[x][y]
        dp2[x][y] = max(dp2[x - 1][y], dp2[x][y - 1]) + coins[x][y]


print(dp1[N - 1][M - 1], dp2[N - 1][M - 1])
