#!/usr/bin/env python3

'''
Текстовый файл 24-j5.txt состоит не более чем из 106 символов S, T, O, C, K. Определите максимальное количество подряд идущих комбинаций «KOT».
'''

s = ''
target = 'KOT'

with open('input.txt') as file:
    s = file.read().replace('\n', '')

n = len(s)
subs = []
for i in range(len(target)):
    subs.append([])
    for j in range(i, n, len(target)):
        subs[i].append(s[j:j + len(target)])


ans, cnt = 0, 0

for sub in subs:
    cnt = 0
    for el in sub:
        ans = max(ans, cnt)
        if el == target:
            cnt += 1
        else:
            cnt = 0
    ans = max(ans, cnt)

print(ans)
