#!/usr/bin/env python3

n, k = map(int, input().split())

data = list(reversed(sorted([int(input()) for _ in range(n)])))

avg1 = sum(data[:k]) / k
avg2 = sum(data[k:2*k]) / k

print(int(avg2), int(avg1))
