#!/usr/bin/env python3

n = int(input())

dp, a = [1] * n, list(map(int, input().split()))

'''
for i in range(1, n):
    for k in range(i):
        if a[i] > a[k]:
            dp[i] = max(dp[i], dp[k] + 1)

print(max(dp))
'''

prev = [-1] * n

for i in range(1, n):
    for k in range(i):
        if a[i] > a[k]:
            if dp[k] + 1 > dp[i]:
                prev[i] = k
                dp[i] = dp[k] + 1


last = 0
for i in range(n):
    if dp[i] > dp[last]:
        last = i


while last != -1:
    print(a[last])
    last = prev[last]



