#!/usr/bin/env python3

'''
Напишите программу, которая ищет среди целых чисел, принадлежащих числовому отрезку [126849; 126871], числа, имеющие ровно 4 различных делителя. Выведите для каждого найденного числа два наибольших делителя в порядке возрастания.
'''

import math

def divisors(n):
    divs, bound = [], int(math.sqrt(n))
    for x in range(1, bound):
        if n % x == 0:
            divs.append(x)
            if n // x != x:
                divs.append(n // x)

    return divs


def ans(n):
    divs = sorted(divisors(n))
    if len(divs) == 4:
        print(divs[-2], divs[-1])


for n in range(126849, 126871 + 1):
    ans(n)


