#!/usr/bin/env python3

n = int(input())

a = [tuple(map(int, input().split())) for _ in range(n)]

dp = [[0 for _ in range(2)]] * n

for i, ((pl, pr), (l, r)) in enumerate(zip(a, a[1:])):
    if pr == l:
        dp[i + 1][0] = max(dp[i + 1][0], dp[i][0] + 1)
    if pr == r:
        dp[i + 1][1] = max(dp[i + 1][1], dp[i][0] + 1)
    if pl == l:
        dp[i + 1][0] = max(dp[i + 1][0], dp[i][1] + 1)
    if pl == r:
        dp[i + 1][1] = max(dp[i + 1][1], dp[i][1] + 1)

print(max(map(lambda p : max(p[0], p[1]), dp)))
