#!/usr/bin/env python3

'''
Рассматриваются целые числа, принадлежащих числовому отрезку [318216; 369453], которые представляют собой произведение трёх различных простых делителей, оканчивающихся на одну и ту же цифру. В ответе запишите количество таких чисел и минимальное из них.
'''


def primes(n):
    def fst(n, d):
        bound = int(n ** 0.5)
        for x in range(d, bound + 1):
            if n % x == 0:
                return x
        return n
    divs, d = [], 2
    while n != 1:
        d = fst(n, d)
        divs.append(d)
        while n % d == 0:
            n //= d

    return divs


a = [0, 10**9]

def ans(n):
    prims = primes(n)
    if len(prims) != 3:
        return
    a1, a2, a3 = prims
    if a1 * a2 * a3 != n:
        return
    if str(a1)[-1] != str(a2)[-1] or str(a2)[-1] != str(a3)[-1]:
        return
    a[0] += 1
    a[1] = min(a[1], n)


for n in range(318216, 369453 + 1):
    ans(n)

print(a[0], a[1])

