#!/usr/bin/env python3

def primes(n):
    '''
    Внутри функции можно объявлять другие функции, бывыает удобно
    функция fst выдает певрый самый маленький делитель числа n, начиная поиск с d.
    самый маленький делитель - простой.
    '''

    def fst(n, d):
        for x in range(d, int(n ** 0.5) + 1):
            if n % x == 0:
                return x
        return n
    divs, d = [], 2
    while n != 1:
        d, mult = fst(n, d), 0

        '''
        Делим пока делится, считая кратность
        '''

        while n % d == 0:
            n //= d
            mult += 1
        divs.append((d, mult))

    return divs


'''
>>> primes(12)
[(2, 2), (3, 1)]

>>> primes(16)
[(2, 4)]

>>> primes(1001)
[(7, 1), (11, 1), (13, 1)]
'''
