#!/usr/bin/env python3

n = int(input())

dp = [0, 0]
mx = 0

for _ in range(n):
    a = int(input())
    ndp = [0, 0]
    if a >= 0:
        ndp[0] = max(dp[0] * a, a)
        ndp[1] = dp[1] * a
    else:
        ndp[0] = dp[1] * a
        ndp[1] = min(a, dp[0] * a)
    mx = max(mx, ndp[0])
    dp = ndp[::]

print(mx)


